### PR TITLE
Split out the host if present in the output of runtime process.

### PR DESCRIPTION
**Pull request by hsluo**
This should fix Khan/frankenserver#3.

### CODE REVIEW

**Comment by csilvers** [comment]
Ah, thank you for the code, that helps clarify things for me.  I hadn't realized this was in the python code and not some go-specific code.

It seems like if this is what exists upstream, the real problem is we haven't been keeping frankenserver up to date with the the upstream releases.  I think the right fix would be to just do that.  (Right now we're against 1.9.25.)  I'll see if I can carve out some time this week.

**Comment by hsluo** [comment]
Sure. Thanks!

**Comment by csilvers** [comment]
OK, I just pushed a new 1.9.36 branch.  I haven't updated master yet since I haven't done a lot of testing, but try out the new branch and see if it fixes things for you!

**Comment by hsluo** [comment]
The port issue is fixed, and haven't seen other things broken. Thanks!

**Pull request closed without merging**
